### ISSUE TITLE
Similar list for other known C2 channels? 

### ISSUE THREAD

**Issue by Brekket** [microsoft/mstic#11]
Hi, really appreciate you maintaining this list, we use it in Sentinel analytic rules for alerting on NordVPN activity. I was wondering if you plan on creating similar lists for Telegram and CactusVPN servers ?

**Comment by ashwin-patil** [comment]
Hey @Brekket Thanks for reaching out. Glad to know the NordVPN list is being used for detection purposes. 

Regarding your query related to other feeds such as Telegram , CactusVPN servers , i have done some research but have not found reliable sources which publish these lists so can't setup one for now. 

Nord VPN is also unique as their API provide unauthenticated feed which makes it easier to share without violating any terms. For others, you may have to rely on third party TI providers , ASN or  whois information.  Hopefully that helps.

**Comment by ashwin-patil** [comment]
Closing this as no further action required.
